{% set python_version = ">=3.6, <3.10" %}
{% set name = "pytest_pytorch" %}
{% set slug = "pytest-pytorch" %}
{% set version = "0.2.1" %}
{% set home = "https://github.com/Quansight/pytest-pytorch" %}

package:
  name: {{ slug }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bf0d4d7a5e618dba1a8503aa626a9711606b0f4733c0df1170fdaac9b3b25724

build:
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps -vv .
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytest

test:
  requires:
    - python {{ python_min }}
  imports:
    - {{ name }}

about:
  home: {{ home }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    pytest plugin for a better developer experience when working with the PyTorch test
    suite
  description: |
    pytest-pytorch is a lightweight pytest-plugin that enhances the developer
    experience when working with the PyTorch test suite if you come from a pytest
    background.
  doc_url: {{ home }}
  dev_url: {{ home }}

extra:
  recipe-maintainers:
    - xmnlab
    - pmeier
